import type { ReceiptDocumentData } from "./types";

export const receiptMockData: ReceiptDocumentData = {
  kind: "receipt",
  orderId: "664fb9f2df2a4b79fd8bc113",
  invoiceNumber: "INV-8BC113A2",
  orderDate: "2026-05-16T10:30:00.000Z",
  paymentStatus: "paid",
  deliveryStatus: "processing",
  customer: {
    fullName: "Amina Njoroge",
    email: "amina@example.com",
    phone: "+254712345678",
    shippingAddress: {
      line1: "Westlands Road",
      line2: "Skyline Residences, Apt 7B",
      city: "Nairobi",
      county: "Nairobi County",
      postalCode: "00100",
      country: "Kenya",
    },
    billingAddress: {
      line1: "Westlands Road",
      line2: "Skyline Residences, Apt 7B",
      city: "Nairobi",
      county: "Nairobi County",
      postalCode: "00100",
      country: "Kenya",
    },
  },
  items: [
    {
      id: "shoe-1",
      name: "Apex Leather Sneaker",
      variant: "Size 41 / Carbon Black",
      size: "41",
      color: "Carbon Black",
      quantity: 1,
      unitPrice: 16990,
      total: 16990,
      imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: "shoe-2",
      name: "Contour Knit Runner",
      variant: "Size 42 / Sand",
      size: "42",
      color: "Sand",
      quantity: 2,
      unitPrice: 11990,
      total: 23980,
      imageUrl: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    },
  ],
  pricing: {
    subtotal: 40970,
    shipping: 990,
    tax: 6555.2,
    discount: 2200,
    couponCode: "LUXE22",
    couponAmount: 2200,
    finalTotal: 46315.2,
    currency: "KES",
  },
  payment: {
    method: "Mobile Money (M-Pesa / Airtel) & Card",
    transactionId: "TRX_20260516_94A81F",
    provider: "Paystack",
    providerReference: "PSK-09411520",
    status: "paid",
    confirmedAt: "2026-05-16T10:31:22.000Z",
    channel: "card",
  },
  note: "Please leave package at concierge desk if unavailable.",
  returnPolicy:
    "Returns are accepted within 14 days from receipt if items are unworn and in original packaging.",
  thankYouMessage:
    "Thank you for choosing TumaFood. Your trust means everything to us.",
  qrCodeUrl: undefined,
  barcodeUrl: undefined,
  currency: "KES",
  locale: "en-KE",
};

